### ISSUE TITLE
Product Carousel 'previous' Button Obscurred

### ISSUE THREAD

**Issue by influxweb** [mivaecommerce/levels-readytheme#61]
https://www.miva.com/forums/forum/designers-and-developers/readytheme/levels-readytheme/696581-storefront-slider-module-prev-and-next-arrow-buttons-problem-solution

https://www.miva.com/forums/forum/designers-and-developers/readytheme/levels-readytheme/682243-sfnt-featured-products

**Comment by influxweb** [comment]
To correct for this in the product carousels, you should be able to add the `z-index` to the pages.css file. If you search for '.product-carousel .slick-next,', update date that call to the following and you should be good to go:
```css
.product-carousel .slick-next,
.product-carousel .slick-prev {
    margin-top: 0;
    top: 32%;
    width: 2.5rem;
    height: 3.5rem;
    z-index: 1;
}
```
I looked at the demonstration site and found the same issue. The above corrected it.
